### ISSUE TITLE
Possibilité d'utilisation sur cloud?

### ISSUE THREAD

**Issue by KostadinovicNikola** [hleroy/teleinfo-linky#1]
Bonjour, pensez vous qu'il serait possible, à la place de la mise en place d'une Raspberry Pi, passer le code dans une fonction Lambda sous AWS et récupérer la téléinfo en la stockant dans S3 ?

**Comment by hleroy** [comment]
Non, il faut un équipement **physique** pour se brancher sur les bornes téléinfo du Linky. Cette page recense de nombreux équipements disponibles sur le marché : https://miniprojets.net/index.php/2022/05/20/etat-de-lart-les-solutions-de-recuperation-des-teleinformations-sur-la-prise-tic-dun-linky/
