### ISSUE TITLE
Pas de répertoire

### ISSUE THREAD

**Issue by Radis35** [hleroy/teleinfo-linky#2]
Bonjour, je débute dans cet environnement. J'ai suivi le tuto mais je bute sur la création des répertoires...

J'ai ce message : mkdir: cannot create directory ‘/home/radis/.config/systemd/user’: No such file or directory

le répertoire linky lui est bien créé.

**Comment by hleroy** [comment]
La commande  `mkdir ~/.config/systemd/user` vise à créer les sous-répertoires `.config/systemd/user` dans votre répertoire personnel. Si cela a bien fonctionné pour le répertoire linky, cela devrait fonctionner également. Je ne peux vous dépanner davantage sur une commande de création de répertoire.

**Comment by Radis35** [comment]
J'ai refait la commande avec -p a la fin et les répertoires ont bien été créés.

**Comment by hleroy** [comment]
Merci de l'info @Radis35. Je vais mettre à jour le README.
